src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Cocur\Slugify\Slugify;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Scalar\Float_;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
#[UniqueEntity('title', message: 'Il existe déjà un produit avec ce titre')]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank]
    private ?string $title;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: false)]
    #[Assert\NotBlank]
    private ?int $price;

    #[ORM\Column]
    private ?string $merchant = null;

    #[ORM\Column]
    private float $weight = 0;

    #[ORM\Column]
    private ?string $category = null;

    #[ORM\Column(type: Types::STRING, nullable: true, length: 255)]
    private ?string $imageFileName = null;

    public function getImageFileName(): ?string
    {
        return $this->imageFileName;
    }
    public function setImageFileName(?string $imageFileName): void
    {
        $this->imageFileName = $imageFileName;
    }
    public function getMerchant(): ?string
    {
        return $this->merchant;
    }

    public function getCategory(): ?string
    {
        return $this->category;
    }

    public function setCategory(?string $category): void
    {
        $this->category = $category;
    }

    public function getWeight(): float
    {
        return $this->weight;
    }

    public function setWeight(float $weight): void
    {
        $this->weight = $weight;
    }

    public function setMerchant(?string $merchant): void
    {
        $this->merchant = $merchant;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(?int $price): static
    {
        $this->price = $price;

        return $this;
    }
    public function getFormattedPrice(): string
    {
        return number_format($this->price, 0, '', ' ');
    }

    public function getSlugify(): string
    {
        $slugify = new Slugify();
        return $slugify->slugify($this->title);
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Repository\ProductRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'home')]
    public function index(ProductRepository $productRepository, EntityManagerInterface $em, UserPasswordHasherInterface $userPasswordHasher): Response
    {
//        $user = new User();
//        $user->setUsername('Mounir')
//            ->setEmail('hassine.mounir1234@gmail.com')
//            ->setPassword($userPasswordHasher->hashPassword($user, 'Mounir'))
//            ->setRoles(['ROLE_ADMIN']);
//        $em->persist($user);
//        $em->flush();

        $products = $productRepository->findLatest();
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'products' => $products
        ]);
    }
}

templates/Home/index.html.twig
{# templates/home/index.html.twig #}

{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
    <div class="jumbotron text-center">
        <h1>Bienvenu dans mon application Symfony!</h1>
        <p>Voici la page d'accueil</p>
    </div>

    <div class="container">
        <h2>Les derniers produits</h2>
        <div class="row flex">
            {% for product in products %}
                <div class="col-3">
                    <div class="card">
                       <div class="card-body">
                           <h5 class="card-title">
                               <a href="{{ path('products.show', {'slugify': product.slugify, 'id': product.id}) }}">
                                   {{ product.title }}
                               </a>
                           </h5>
                            <div class="text-primary" style="font-weight: bold; font-size: 2rem">
                                {{ product.formattedPrice }} €
                            </div>
                           <p class="card-text">
                               {{ product.description }}
                           </p>

                       </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}